# Generated by Django 4.2.7 on 2023-11-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_name', models.CharField(max_length=50, verbose_name='Назва туру')),
                ('description', models.TextField(verbose_name='Опис туру')),
                ('travel_time', models.CharField(max_length=50, verbose_name='Тривалість туру')),
                ('price', models.IntegerField(verbose_name='Ціна')),
            ],
        ),
    ]
