# Generated by Django 4.2.7 on 2023-11-30 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='travel',
            options={'verbose_name': 'Тур', 'verbose_name_plural': 'Тури'},
        ),
    ]
