# Generated by Django 4.2.7 on 2023-12-08 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0002_alter_travel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='country',
            field=models.TextField(default=None, verbose_name='Країна'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travel',
            name='time_go',
            field=models.TimeField(default=None, verbose_name='Час вильоту'),
            preserve_default=False,
        ),
    ]
