# Generated by Django 4.2.7 on 2023-12-08 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0003_travel_country_travel_time_go'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='country',
        ),
        migrations.RemoveField(
            model_name='travel',
            name='time_go',
        ),
    ]
