# Generated by Django 4.2.7 on 2023-12-08 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0004_remove_travel_country_remove_travel_time_go'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Країна'),
        ),
    ]
