# Generated by Django 4.2.7 on 2023-12-08 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0005_travel_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='time_go',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Час вильоту'),
        ),
    ]
