# Generated by Django 4.2.7 on 2023-12-19 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0007_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user_email',
            field=models.EmailField(max_length=254, verbose_name='Електронна пошта'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_lname',
            field=models.CharField(max_length=100, verbose_name='Фамілія'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_name',
            field=models.CharField(max_length=100, verbose_name='Ім`я'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_phone',
            field=models.CharField(max_length=20, verbose_name='Номер телефону'),
        ),
    ]
